services:
  - type: web
    name: witaudiotextconvert-tts
    runtime: python
    plan: free
    buildCommand: pip install -r render-requirements.txt
    startCommand: python render-app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0